addIngredient("dalgona_cookie",{
    type:"cookie",
    color:"#E2C576",
    shape:"fisheye",
    scale:1.0,
    keywords:"media,squid,squid_game,dalgona,cookie",
    dishName:"dalgona_cookies",
    adj:"dalgona",
    broken:"breadcrumbs"
  });
