addIngredient("dalgona_cookie",{
    type:"cookie",
    color:"#E2C576",
    shape:"fisheye",
    scale:1.0,
    keywords:"media,squid,squid_game,dalgona,cookie",
    dishName:"dalgona_cookies",
    adj:"dalgona",
    broken:"breadcrumbs"
  });

addIngredient("jamal",{
    type:"doll",
    color:"#4F3C2F",
    shape:"figure",
    scale:4.0,
    keywords:"meme,jamal,kid,human,doll,black,idk",
    dishName:"jamal",
    adj:"jamal",
  });

addIngredient("the_observable_universe",{
    type:"water",
    color:"#000000",
    shape:"square_round",
    scale:9999.0,
    keywords:"meme,universe,space,big,pleasehelpihavebeenstuckherefor10months",
    dishName:"universe",
    adj:"universal",
  });
